export default {
  namespace: 'emotions',
  state: [
    {
      src: require('@/assets/smile/biggrin.png'),
      name: 'biggrin',
      title: '咧嘴',
    }, {
      src: require('@/assets/smile/cogitate.png'),
      name: 'cogitate',
      title: '思考',
    }, {
      src: require('@/assets/smile/cry.png'),
      name: 'cry',
      title: '大哭',
    }, {
      src: require('@/assets/smile/dizzy.png'),
      name: 'dizzy',
      title: '晕',
    }, {
      src: require('@/assets/smile/grimacing.png'),
      name: 'grimacing',
      title: '鬼脸',
    }, {
      src: require('@/assets/smile/huffy.png'),
      name: 'huffy',
      title: '发怒',
    }, {
      src: require('@/assets/smile/laugh.png'),
      name: 'laugh',
      title: '哭笑',
    }, {
      src: require('@/assets/smile/lol.png'),
      name: 'lol',
      title: '大笑',
    }, {
      src: require('@/assets/smile/loveliness.png'),
      name: 'loveliness',
      title: '可爱',
    }, {
      src: require('@/assets/smile/plead.png'),
      name: 'plead',
      title: '可怜',
    }, {
      src: require('@/assets/smile/sad.png'),
      name: 'sad',
      title: '难过',
    }, {
      src: require('@/assets/smile/shocked.png'),
      name: 'shocked',
      title: '震惊',
    }, {
      src: require('@/assets/smile/shutup.png'),
      name: 'shutup',
      title: '闭嘴',
    }, {
      src: require('@/assets/smile/sleepy.png'),
      name: 'sleepy',
      title: '睡觉',
    }, {
      src: require('@/assets/smile/smile.png'),
      name: 'smile',
      title: '微笑',
    }, {
      src: require('@/assets/smile/supercilious.png'),
      name: 'supercilious',
      title: '傲慢',
    }, {
      src: require('@/assets/smile/sweat.png'),
      name: 'sweat',
      title: '流汗',
    }, {
      src: require('@/assets/smile/titter.png'),
      name: 'titter',
      title: '偷笑',
    }, {
      src: require('@/assets/smile/tongue.png'),
      name: 'tongue',
      title: '吐舌',
    }, {
      src: require('@/assets/smile/untitled.png'),
      name: 'untitled',
      title: '发呆',
    }, {
      src: require('@/assets/smile/victory.png'),
      name: 'victory',
      title: '胜利',
    }, {
      src: require('@/assets/smile/handshake.png'),
      name: 'handshake',
      title: '握手',
    }, {
      src: require('@/assets/smile/ok.png'),
      name: 'ok',
      title: '好的',
    }, {
      src: require('@/assets/smile/like.png'),
      name: 'like',
      title: '赞',
    }
  ],
};
